default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: hack2save_development


test:
  <<: *default
  database: hack2save_test


production:
  <<: *default
  database: hack2save_production
  username: hack2save
  password: <%= ENV['HACK2SAVE_DATABASE_PASSWORD'] %>
