# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f4dc56f14d0b11b8f05c01a13c3a06414e265cd11d8af1079ba1a93dd2689252fed1017ee6a743d9646caae3c165bd944d53da71b993f3535c21ec8aaaf1ad8

test:
  secret_key_base: a4cd202c007f706f31b3b0b1da716ec7736075d2f60e512e1e6acd078d3ebc88c40916de497a7eb8502dc2cd4201748fc2e1f43d39b03a1ffe4217ce1a8f8225

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
